# Generated by Django 3.2 on 2022-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="user_email",
            field=models.EmailField(max_length=254),
        ),
    ]
