# Generated by Django 3.2 on 2022-01-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
