# Generated by Django 3.2 on 2022-01-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_delete_gin_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="requests",
        ),
    ]
