# Generated by Django 3.2 on 2022-01-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
