# Generated by Django 3.2 on 2022-01-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20220113_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
