# Generated by Django 3.2 on 2022-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0016_auto_20220114_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="for_how_many",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(),
        ),
    ]
