# Generated by Django 3.2 on 2022-01-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0020_auto_20220114_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="for_how_many",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(),
        ),
    ]
