# Generated by Django 3.2 on 2022-01-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_auto_20220120_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Other', 'Other')], default='Other', max_length=6),
        ),
    ]
