# Generated by Django 3.2 on 2022-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_reservation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Other', 'Other')], max_length=6),
        ),
    ]
